---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    lemmy.service: lemmy
  name: lemmy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        lemmy.service: lemmy
    spec:
      containers:
      - env:
        - name: LEMMY_DATABASE_URL
          # example: 'postgres://lemmy:password@db:5432/lemmy'
          value: CHANGE_ME
        - name: LEMMY_HOSTNAME
          # example: 'lemmy.example.com'
          value: CHANGE_ME
        - name: LEMMY_JWT_SECRET
          # example: 'very-super-good-secret'
          value: CHANGE_ME
        - name: LEMMY_FRONT_END_DIR
          value: /app/dist
        image: dessalines/lemmy:v0.2.0.1
        name: lemmy
        ports:
        - containerPort: 8536
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    lemmy.service: lemmy
  name: lemmy
spec:
  ports:
  - name: "8536"
    port: 8536
    targetPort: 8536
  selector:
    lemmy.service: lemmy
